<a href="https://colab.research.google.com/github/chamanoy05/Lessons-at-Mohirdev/blob/main/arifmetik%2C_statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [ ]:
#ko'paytish
arr1*arr2 # arr1 ni arr2 ning mos elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
#bo'lish
arr1/arr2 #arr1 ni arr2 ning mos elementlariga bo'lib beradi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [ ]:
# qo'shish
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
#ayrish
arr2- arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
#kvadratga oshirish
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
#darajaga oshirish
arr2**4

array([[ 1296,  2401,  4096],
       [ 6561, 10000, 14641]])

arifmetik va statistik amallar

cumsum - yig'ilib boriladigan cumulative yig'indi

cumprod - yig'ilib boradigan ko'paytma

In [ ]:
#data
arr = np.random.randn(5, 4)
arr

array([[-0.82446568, -1.24456688, -1.02408819, -1.75887881],
       [-0.79170466, -0.04688508, -0.20834915,  1.04223854],
       [ 1.83898366, -0.04004051, -2.55907647,  0.44404646],
       [ 0.46539876,  1.29351101, -0.76643095, -1.06644406],
       [-1.59417668,  1.94732635,  0.20140556, -1.12404269]])

In [ ]:
#sum metodi
arr.sum() # arraydagi barcha elementlar yig'indisi

-5.816239460910689

In [ ]:
np.sum(arr) #arraydagi barcha elementlar yig'indisi

-5.816239460910689

In [ ]:
arr.sum(axis=1) # qator bo'yicha yig'indi

array([-4.85199955e+00, -4.70034527e-03, -3.16086861e-01, -7.39652384e-02,
       -5.69487464e-01])

In [ ]:
arr.sum(axis=0) # ustun bo'yicha yig'indi

array([-0.9059646 ,  1.90934489, -4.35653919, -2.46308056])

In [ ]:
#mean metodi
data = np.arange(1, 5)
np.sum(data)/5

2.5

In [ ]:
np.mean(data)

2.5

In [ ]:
data.mean

<function ndarray.mean>

In [ ]:
np.mean(arr, axis=1) #qator bo'yicha o'rtacha qiymat

array([-1.21299989e+00, -1.17508632e-03, -7.90217153e-02, -1.84913096e-02,
       -1.42371866e-01])

In [ ]:
np.mean(arr, axis=0) #ustun bo'yicha o'rtacha qiymat

array([-0.18119292,  0.38186898, -0.87130784, -0.49261611])

In [ ]:
#consum metodi
data

array([1, 2, 3, 4])

In [ ]:
arr= np.random.randn(4)
#sort funksiyasi
arr_sorted= np.sort(arr) #arr massivning tartiblangan versiyasi
arr_sorted

array([-1.89310572, -0.26586941,  0.13564414,  0.44298758])

In [ ]:
arr.sort
arr

array([-0.26586941,  0.13564414,  0.44298758, -1.89310572])

In [ ]:
#teskari tartiblash
rev_arr = -np.sort(-arr) # arrayni teskari tartibdagi versiyasi
rev_arr

array([ 0.44298758,  0.13564414, -0.26586941, -1.89310572])

In [ ]:
# 2D array massiv
arr2d = np.random.randn(2, 4)
arr2d.ndim
arr2d

array([[ 1.4400552 ,  1.39424271,  0.80038118, -0.18430887],
       [-0.21928576,  1.85128201, -1.20731758, -1.15436774]])

In [ ]:
# axis = 0  qator o'qi
raw_sorted= np.sort(arr2d, axis=0) #arr2d ning har bir qator bo'yicha tartiblangan shakli
raw_sorted


array([[-0.21928576,  1.39424271, -1.20731758, -1.15436774],
       [ 1.4400552 ,  1.85128201,  0.80038118, -0.18430887]])

In [ ]:
# axis = 1 ustun o'qi
column_sorted= np.sort(arr2d, axis=1)
column_sorted

array([[-0.18430887,  0.80038118,  1.39424271,  1.4400552 ],
       [-1.20731758, -1.15436774, -0.21928576,  1.85128201]])