<a href="https://colab.research.google.com/github/chamanoy05/Lessons-at-Mohirdev/blob/main/massivga_yo'naltirilgan_dasturlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

massiv operatorlarini shart operatorlari o"rnida qo'llash

shart operatori sifatida where dan foydalanish


In [ ]:
#massivlar
xarr = np.array([1.1,  1.2,  1.3,  1.4,  1.5])
yarr = np.array([2.1,  2.2,  2.3,  2.4,  2.5])


In [ ]:
#shart
cond  =  np.array([True, False, True, True, False])


In [ ]:
#where
result= np.where(cond, xarr, yarr) #cond agr true bo'lsa xarr dagi element, agar False bo'lsa yarr dagi element qaytaradi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr= np.random.randn(3, 3)
arr

array([[ 1.75964627,  0.04855577, -0.01095308],
       [-0.15241635, -0.88347774,  1.14356014],
       [-0.54372798, -0.97252817,  1.52278414]])

In [ ]:
#where
result= np.where(arr<0, -2, 2) # arr elementlarini manfiy bo'lsa-2 ga; musbat bo'lsa 2 ga almashtirish
result


array([[ 2,  2, -2],
       [-2, -2,  2],
       [-2, -2,  2]])

In [ ]:
arr

array([[ 1.75964627,  0.04855577, -0.01095308],
       [-0.15241635, -0.88347774,  1.14356014],
       [-0.54372798, -0.97252817,  1.52278414]])

In [ ]:
np.mean(arr)

0.21238255595992583

In [ ]:
#cumsum metodi
data= np.arange(5)