<a href="https://colab.research.google.com/github/chamanoy05/Lessons-at-Mohirdev/blob/main/takrorlanmas_b_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

unique,

In [ ]:
import numpy as np

In [ ]:
names = np.array(['Anvar', 'Nozima', 'Hoshim', 'Sabrina', 'Anvar'])
numbers= np.array([ 2, 3, 2, 1, 1, 2])
np.unique(names)




array(['Anvar', 'Hoshim', 'Nozima', 'Sabrina'], dtype='<U7')

In [ ]:
np.unique(numbers)#numbersdagi takrorlanmas sonlarni qaytaradi(takrorlansayam bittasi takrorlanadi

array([1, 2, 3])

In [ ]:
#set
set(names)

{'Anvar', 'Hoshim', 'Nozima', 'Sabrina'}

In [ ]:
#data
arr1=np.array([1, 2, 4, 9, 7])
arr2=np.array([ 1, 4, 5, 9, 2, 0, 3])
#inld usuli
np.in1d(arr1, arr2) #arr1 elementlari arr2 da bo'lgan yoki bo'lmaganligini tekshirish
#setdifld usuli

array([ True,  True,  True,  True, False])

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])