<a href="https://colab.research.google.com/github/chamanoy05/Lessons-at-Mohirdev/blob/main/Tranposing_Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

massivlarni positsiyalarini ko'chirish- Transpose


o'qlar o'rnini almashtirish- Swapping

In [ ]:
A = np.arange(6).reshape(3, 2) # A massiv elementlar soni 0 dan 6 gacha;shape(2, 3)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.T # A massivning transpose ko'rinishini olish

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A.swapaxes(1, 0) # A massivni transpose ko'rinishida berish

array([[0, 2, 4],
       [1, 3, 5]])

Swapaxes ko'p

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.dot(A, A.T) # A massiv va A.T dan hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])