<a href="https://colab.research.google.com/github/chamanoy05/Lessons-at-Mohirdev/blob/main/universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Universal funksiyalar


Unary fuksiyalar bitta argument qabul qiluvchi funksiyalar

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sqrt massiv har bir elementidan kvadrat ildiz qaytaradi

In [ ]:
np.sqrt(arr1) # arr1 nomli massivning barcha elementlaridan kvadrat ildiz qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

square funksiyasi har bir elementni kvadratga ko'taradi

In [ ]:
np.square(arr1) # arr1 nomli massivning barcha elementlarini kvadratga oshirish

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arr1) # arr1 noli massivdagi barcha elementlaridan exponential olish

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr1) # arr1 nomli massivdagi har bir sonni logarifmini hisoblash

<ipython-input-9-61170a6c4415>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1) # arr1 nomli massivdagi har bir sonni logarifmini hisoblash


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

modf funksiyasi haqiqiy sonlarni butun va qoldiq qismlarini ajratib olish

In [ ]:
arr2=np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr2

array([ 2.01763218,  0.02044381, -0.22087953,  0.7401971 , -1.60900298,
       -1.17287941])

In [ ]:
qoldiq, butun = np.modf(arr2)
qoldiq, butun

(array([ 0.01763218,  0.02044381, -0.22087953,  0.7401971 , -0.60900298,
        -0.17287941]),
 array([ 2.,  0., -0.,  0., -1., -1.]))

sign funksiyasi massiv elementlari manfiy bo'lsa -1, musbat bo'lsa +1 qaytaradi

In [ ]:
np.sign(arr2) # arr2 massivdagi elementlarini ishoralarini qaytaradi

array([ 1.,  1., -1.,  1., -1., -1.])

isnan massivdagi elementlarda NaN ma'lumoti bo'sa True ni, bo'lmasa False ni qaytaradi

In [ ]:
np.isnan(arr2)

array([False, False, False, False, False, False])

In [ ]:
arr2[0]= np.NaN
arr2

array([        nan,  0.02044381, -0.22087953,  0.7401971 , -1.60900298,
       -1.17287941])

In [ ]:
np.isnan(arr2)

array([ True, False, False, False, False, False])

Binary funksiyalar (ikkita argument qabul qiluvchi funksiyalar)

add, multiply, maximum...

add ikkita massivning mos elementlarini qo'shadi

In [ ]:
arr3= np.random.randn(5)
arr4= np.random.randn(5)

In [ ]:
arr3

array([ 0.43350086,  0.15812501, -2.19880391,  0.34819315,  0.46423176])

In [ ]:
arr4

array([-0.86567634,  0.82821579,  2.64038923, -1.33129707, -1.59724488])

In [ ]:
np.add(arr3, arr4) #arr3 va arr4 massivlarini bir biriga mos elementlarini qo'shish

array([-0.43217548,  0.9863408 ,  0.44158532, -0.98310392, -1.13301312])

In [ ]:
arr3+arr4

array([-0.43217548,  0.9863408 ,  0.44158532, -0.98310392, -1.13301312])

In [ ]:
np.multiply(arr3, arr4) #arr3 va arr4 massivlarni mos elementlarini ko'paytirish

array([-0.37527144,  0.13096163, -5.80569816, -0.46354852, -0.74149179])

maximum ikkita massivning mos elementlarini taqqoslab ulardan maximumini qaytaradi

In [ ]:
np.maximum(arr3, arr4) #arr3 va arr4 mos elementlaridan kattasini elementini olish

array([0.43350086, 0.82821579, 2.64038923, 0.34819315, 0.46423176])